name: ClusteredNetwork_pub
channels:
  - soumith
  - defaults
  - conda-forge
dependencies:
  - scipy
  - notebook
  - ipython
  - nest-simulator=2.16.0
  - pip
  - pip:
    - latex
    - pyx
  - python=3.6
  - joblib
  - networkx
  - scikit-learn
  - matplotlib=3.1

